new_git_repository(
  name = "googletest",
  build_file = "gtest.BUILD",
  remote = "https://github.com/google/googletest.git",
  tag = "release-1.8.0",
)

new_git_repository(
  name = "googlebench",
  build_file = "gbench.BUILD",
  remote = "https://github.com/google/benchmark.git",
  tag = "v1.3.0",
)
