[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.1"
edition = "2024"
authors = ["Alex Conley <alexanderconley@gmail.com>"]

[workspace.dependencies]
lazy_static = "1.5.0"
petgraph = "0.8.3"
rustsat = "0.7.5"
rustsat-cadical = "0.7.5"
criterion = "0.8"
claim = "0.5"
lending-iterator = "0.1.7"
